services:
  web:
    build:
      context: .
    ports:
      - 8000:5000
    volumes:
      - ./:/app

  mysqldb:
    image: mysql:8.0
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=p@ssw0rd1


volumes:
  mysql:
  mysql_config:
